// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.DbContexts;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230221041228_ProductDB")]
    partial class ProductDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Model.ProductDto", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Pet",
                            Description = "Dog",
                            ImageUrl = "",
                            Name = "Shiba Inu",
                            Price = 1.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Pet",
                            Description = "Dog",
                            ImageUrl = "",
                            Name = "Dogger Coin",
                            Price = 12.0
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Pet",
                            Description = "Dog",
                            ImageUrl = "",
                            Name = "Aslaska",
                            Price = 23.0
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Pet",
                            Description = "Dog",
                            ImageUrl = "",
                            Name = "Bug France",
                            Price = 30.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
